### ISSUE TITLE
General approach to converting this into a R3F component?

### ISSUE THREAD

**Issue by jeffscottward** [mrdoob/xrcode#1]
I'm trying to follow along with the code but there are extra modules unrelated to Three.js that I'm unsure if they can be dumped. 

Is mocking this up in R3F doable? Perhaps build issues relating to JSX requiring a different setup?

Thoughts?

https://github.com/pmndrs/drei#html

**Comment by mrdoob** [comment]
What unrelated modules do you mean?

**Comment by jeffscottward** [comment]
> What unrelated modules do you mean?

Oops, Javascript.js is not a shim file it's a language syntax file for the text editor and Textor is the editor. Didn't quite get that for a second. And ConsoleTexture is the container basically.

And the actual shim file is for import maps which may not even apply given a build process with JSX.

Hmmm the code is actually pretty self explanatory.

A lot of it I can move into functions or hooks outside of the JSX render tree, and hopefully use setState for code content and updates.

I think it's doable. Might not need help. Just don't know if the editor can be fully encapsulated as an R3F drei module, but maybe.

If the world just gained a drop in <LiveCodeEditor/> oh man.

Gonna try this.

EDIT: it just occurred to me that that I may need two servers because authoring in R3F not straight Three.js in the editor will require a build process. Unless perhaps it can someone be done in the browsers entirely (not likely).

**Comment by jeffscottward** [comment]
> > What unrelated modules do you mean?
> 
> Oops, Javascript.js is not a shim file it's a language syntax file for the text editor and Textor is the editor. Didn't quite get that for a second. And ConsoleTexture is the container basically.
> 
> And the actual shim file is for import maps which may not even apply given a build process with JSX.
> 
> Hmmm the code is actually pretty self explanatory.
> 
> A lot of it I can move into functions or hooks outside of the JSX render tree, and hopefully use setState for code content and updates.
> 
> I think it's doable. Might not need help. Just don't know if the editor can be fully encapsulated as an R3F drei module, but maybe.
> 
> If the world just gained a drop in <LiveCodeEditor/> oh man.
> 
> Gonna try this.
> 
> EDIT: it just occurred to me that that I may need two servers because authoring in R3F not straight Three.js in the editor will require a build process. Unless perhaps it can someone be done in the browsers entirely (not likely).

And it would need to be a remote session into VSCode so you can reach the terminal. Uh oh.

**Comment by jeffscottward** [comment]
But then if it is VSCode for Web

https://code.visualstudio.com/docs/editor/vscode-web

How do you render on your side? Would need a tunnel to send updates to session container, but decompiled to raw Three.JS? 

Some infinite loop / chicken and egg stuff here.

The entire thing needs to be able to be done in browser, build steps and all. 

I think this enters WASM land.

Am I wrong?

**Comment by jeffscottward** [comment]
Hmmm Babel directly in browser may work.

https://datacadamia.com/web/javascript/react/jsx_browser

Or Preact?
Hope may not be lost.
More research is needed.

EDIT: From babel docs

https://babeljs.io/docs/babel-standalone

```html
<div id="output"></div>
<!-- Load Babel -->
<!-- v6 <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script> -->
<script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
<!-- Your custom script here -->

<script type="text/jsx" data-type="module" data-presets="env,react,typescript">
  // code
</script>
```

https://stackoverflow.com/questions/40230101/single-react-component-rendering-with-babel-standalone-with-only-index-html-and

**Comment by jeffscottward** [comment]
OK wrote this up but getting a babel error.
Thoughts?

https://github.com/jeffscottward/R3F-VR-Client/blob/main/index.html

Inline Babel script:5 Uncaught ReferenceError: require is not defined
    at <anonymous>:4:14

**Comment by jeffscottward** [comment]
It works! Mostly...

I had to put `imports` on the `window` object to get around an ES6 import bug for `babel/standalone`.
I found a great  CDN tool for ESM modules because that was being quite a pain. https://esm.sh/
Fun fact: `importmap` is natively supported now. No more shims.

I filed a bug about the babel issue importing ES6 modules.
https://github.com/babel/babel/issues/15914

And here is the working-ish code
https://github.com/jeffscottward/R3F-VR-Client/blob/main/index.html

<img width="971" alt="Screenshot 2023-08-31 at 7 27 15 PM" src="https://github.com/mrdoob/xrcode/assets/1263486/41b27bb4-2d47-4eb2-ba24-fc052fa04a57">

**Comment by mrdoob** [comment]
Nicely done!
Do you have a live link? 🤔

**Comment by jeffscottward** [comment]
> Nicely done! Do you have a live link? 🤔

Nope but it’s totally copy paste able, static HTML.
And sorry I misspoke, by “working” i mean just generally R3F with the window caveat.

I still need to do the whole conversion of this repo from THREE to R3F 😅. The ESM & Babel hill was climbed though.

**Comment by jeffscottward** [comment]
imports working!
Babel present env was not needed.
now time to fork and convert the code to r3f.

closing this. will submit a branch PR for r3f, or perhaps a bool flag version for using r3f
